INFO:root:Executed R('load(\'../../instructor/assignments/hw1/hw1-tests.rda\')')
INFO:root:(2 points) R('all.equal(y, sol$y)')[0] is True
INFO:root:(2 points) R('all.equal(z, sol$z)')[0] is True
ERROR:root:(2 points) Checking R('all.equal(z, sol$z1)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   20 string mismatches
INFO:root:(2 points) R('all.equal(m, sol$m)')[0] is True
ERROR:root:(2 points) Checking R('all.equal(mean.m, sol$mean.m)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/andyatcal/Library/Python/2.7/lib/python/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(mean.m, sol$mean.m) : object 'mean.m' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/andyatcal/Library/Python/2.7/lib/python/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(mean.m, sol$mean.m) : object 'mean.m' not found

Traceback (most recent call last):
  File "/Users/andyatcal/Library/Python/2.7/lib/python/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(mean.m, sol$mean.m) : object 'mean.m' not found

ERROR:root:(2 points) Checking R('all.equal(sd.m, sol$sd.m)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/andyatcal/Library/Python/2.7/lib/python/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(sd.m, sol$sd.m) : object 'sd.m' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/andyatcal/Library/Python/2.7/lib/python/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(sd.m, sol$sd.m) : object 'sd.m' not found

Traceback (most recent call last):
  File "/Users/andyatcal/Library/Python/2.7/lib/python/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rpy2/robjects/__init__.py", line 269, in __call__
    res = self.eval(p)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(sd.m, sol$sd.m) : object 'sd.m' not found

INFO:root:(2 points) R('all.equal(max.m, sol$max.m)')[0] is True
INFO:root:(2 points) R('all.equal(bmi, sol$bmi)')[0] is True
ERROR:root:(2 points) Checking R('all.equal(family.men, sol$family.men)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Names: 3 string mismatches
ERROR:root:(2 points) Checking R('all.equal(family.young, sol$family.young)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Names: 2 string mismatches
ERROR:root:(2 points) Checking R('all.equal(family2, sol$family2)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Names: 1 string mismatch
INFO:root:You got a 10 out of 20.
